services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # backend:
  #   build:
  #     context: ./backend
  #     target: test
  #   command: python -m pytest
  #   volumes:
  #     - ./backend:/app
  #   env_file:
  #     - .env

  backend-prod:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
